"""add user_strengths table

Revision ID: 1fc597e57c19
Revises: 2eaa9d975b79
Create Date: 2026-01-13 15:29:44.268310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fc597e57c19'
down_revision: Union[str, Sequence[str], None] = '2eaa9d975b79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_strengths',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('top_strengths', sa.Text(), nullable=True),
    sa.Column('areas_for_improvement', sa.Text(), nullable=True),
    sa.Column('learning_style', sa.String(), nullable=True),
    sa.Column('communication_preference', sa.String(), nullable=True),
    sa.Column('sharing_boundaries', sa.Text(), nullable=True),
    sa.Column('goals', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_strengths_user_id'), 'user_strengths', ['user_id'], unique=True)
    # Autogeneration detected changes in other tables (e.g. indexes), keeping them focused for now.
    # If other indexes are missing, they should be in their own migration.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_strengths_user_id'), table_name='user_strengths')
    op.drop_table('user_strengths')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
