"""Add tooltip to questions

Revision ID: 40a2a7999481
Revises: b33b18452387
Create Date: 2026-01-07 14:10:51.382679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40a2a7999481'
down_revision: Union[str, Sequence[str], None] = 'b33b18452387'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_bank', sa.Column('tooltip', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question_bank', 'tooltip')
    # ### end Alembic commands ###
