"""Add profile enhanced columns

Revision ID: 64a9bde24d3d
Revises: cd7e021130c1
Create Date: 2026-01-15 11:21:39.465785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64a9bde24d3d'
down_revision: Union[str, Sequence[str], None] = 'cd7e021130c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('question_metadata')
    with op.batch_alter_table('medical_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ongoing_health_issues', sa.Text(), nullable=True))

    with op.batch_alter_table('personal_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('high_pressure_events', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_profiles', schema=None) as batch_op:
        batch_op.drop_column('high_pressure_events')

    with op.batch_alter_table('medical_profiles', schema=None) as batch_op:
        batch_op.drop_column('ongoing_health_issues')

    op.create_table('question_metadata',
    sa.Column('question_id', sa.INTEGER(), nullable=False),
    sa.Column('source', sa.VARCHAR(), nullable=True),
    sa.Column('version', sa.VARCHAR(), nullable=True),
    sa.Column('tags', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('question_id')
    )
    # ### end Alembic commands ###
